# Generated by Django 5.0.4 on 2024-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_item_first_name_remove_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
